# -*- coding: utf-8 -*-
"""FIX_Sistem_Rekomendasi_Rev_Lazada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hATM7-z9WK498AfxmH9E9KP2T-LSPdyi

## Business Understanding

### Problem Statements
Berdasarkan kondisi yang telah dijelaskan sebelumnya, muncul beberapa pertanyaan penting, yaitu:
- Bagaimana sistem rekomendasi berbasis kesamaan kategori produk dapat membantu pengguna menemukan produk lain yang relevan?
- Bagaimana sistem ini dapat memberikan rekomendasi dengan memanfaatkan informasi kategori dan tingkat popularitas produk berdasarkan rating?
- Bagaimana sistem ini dapat merekomendasikan produk berdasarkan kategori serta kualitas produk yang diukur melalui jumlah rekomendasi dari pengguna?

### Goals
Proyek analisis prediktif ini bertujuan utama untuk menjawab pertanyaan-pertanyaan tersebut. Secara lebih rinci, tujuan yang ingin dicapai meliputi:
- Menyediakan rekomendasi produk yang relevan menggunakan pendekatan Content-Based Filtering berbasis kesamaan kategori produk
- Menggunakan informasi kategori dan rating produk untuk menampilkan produk-produk serupa yang lebih relevan bagi pengguna
- Menggunakan informasi kategori serta jumlah total rekomendasi dari pengguna untuk menampilkan produk serupa yang lebih akurat

### Solution statements
Solusi yang ditawarkan adalah dengan menerapkan Content-Based Filtering menggunakan metode TF-IDF dan Cosine Similarity.

Pendekatan ini menggunakan representasi teks produk dengan teknik TF-IDF (Term Frequency-Inverse Document Frequency) untuk mengukur tingkat pentingnya kata-kata pada kategori produk. Setiap produk akan diubah menjadi vektor berdasarkan kata-kata kunci dalam kategorinya, lalu dihitung kesamaan antar produk menggunakan cosine similarity. Dengan metode ini, sistem dapat merekomendasikan produk kepada pengguna berdasarkan kesamaan kategori dengan produk yang sebelumnya mereka pilih.

## Data Understanding

Dataset berisi 3961 baris dan 6 kolom, dataset terdiri dari Kolom-kolomnya berisi brand_name, product_name, product_id, beauty_point_earned, price_range, price_by_combinations, url, active_date, default_category, categories, rating_types_str, average_rating, total_reviews, average_rating_by_types, total_recommended_count, total_repurchase_maybe_count, total_repurchase_no_count, total_repurchase_yes_count, total_in_wishlist. Variabel yang akan digunakan pada kasus kali ini sebagai parameter rekomendasi adalah variabel default_category. Kondisi data masih belum bersih dengan ditandai masih adanya missing values.

Referensi:
Nugroho. "Product Data E-Commerce Lazada". Tautan: [https://www.kaggle.com/datasets/intodarkmoon/product-data-e-commerce-lazada]. Diakses pada 27 April 2025.

## Data Loading
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline
import seaborn as sns

products = pd.read_csv('lazada_data.csv')
products

"""- Data berhasil terpanggil, di sini data terdiri dari 3961 baris dan 6 kolom.
- Kolom-kolomnya berisi Name, Rating Score, Total Review, Seller Name, Location, dan Price (IDR).

## Univariate Exploratory Data Analysis

Variabel-variabel pada dataset adalah sebagai berikut:
- Name: nama produk
- Rating Score: penilaian produk oleh customer
- Total Review: Berapa banyak customer yang melakukan review
- Seller Name: Nama penjual.
- Location: lokasi toko offline / gudang.
- Price (IDR): Harga barang dalam mata uang Rupiah.
"""

products.info()

print('Jumlah Name: ', len(products.Name.unique()))
print('Jumlah Seller Name: ', len(products['Seller Name'].unique()))
print('Jumlah Rating Score: ', len(products['Rating Score'].unique()))
print('Jumlah Location: ', len(products.Location.unique()))

"""Dengan fungsi unnique, dapat diketahui jika dataaset terdiri dari 3796 nama produk yang berbeda, 304 nama toko yang berbeda, 510 nilai rating yang berbeda, dan 69 lokasi pedagang yang berbeda

## Data Preparation

#### Memeriksa Data Terduplikasi
"""

products.duplicated().sum()

"""Data memiliki 9 data terduplikasi. Selanjutnya akan menghilangkan data terduplikasi tersebut."""

products.drop_duplicates(inplace=True)

products.duplicated().sum()

"""Sekarang, data duplikasi sudah tidak ada.

#### Mengatasi Missing Value
"""

products.describe()

products.isnull().sum()

"""terdapat banyak missing values di dua kolom, yaitu 'Rating Score' dan 'Total Review'. Oleh sebab itu, baris pada dataset yang memiliki missing value pada kolom tersebut akan di drop, karena memiliki missing values dan nilai yang tidak terlalu berpengaruh terhadap tujuan rekomendasi."""

#Baris yang tidak terlalu berpengaruh dan memiliki NaN didrop
products.dropna(subset=['Rating Score', 'Total Review'], inplace=True)
products

"""Dapat, dilihat, baris yang memiliki missing value berhasil dihapus."""

products.isnull().sum()

"""Setelah diperiksa, nilai missing values sudah tidak ada

#### TF-IDF Vectorizer

Teknik TF-IDF digunakan pada sistem rekomendasi untuk menemukan representasi fitur penting dari setiap kategori produk.
"""

products

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
tf.fit(products['Name'])
tf.get_feature_names_out()

tfidf_matrix = tf.fit_transform(products['Name'])
tfidf_matrix.shape

"""Matriks berukuran (1720, 1176). Nilai 1720 merupakan ukuran data dan 1176 merupakan matrik kategori produk atau banyaknya tipe dari kategori produk"""

tfidf_matrix.todense()

"""Selanjutnya, matriks tf-idf untuk nama produk dan kata kunci produk."""

pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tf.get_feature_names_out(),
    index=products['Name'].values
).sample(50, axis=1).sample(50, axis=0)

"""Output sampel matriks tf-idf di atas menunjukkan 'REALME C33 4/128GB vs 4/64GB vs 3/32GB | OS Android 12, Realme UI S | Chipset Unisoc Tiger T612 (12 nm)' mengandung kata kunci '12'. Hal ini terlihat dari nilai matriks 0.277793 pada kategori kata kunci '12'. Begitu juga dengan 'Redmi 12 8/128/256GB MediaTek Helio G88 Garansi Resmi', termasuk dalam kategori kata kunci yang sama, dengan nilai 0.324161.

## Model Development dengan Content Based Filtering berdasarkan Kategori Produk

Teknik content based filtering akan merekomendasikan item yang mirip dengan item yang disukai pengguna di masa lalu. Pada tahap ini, ditemukan representasi fitur penting dari setiap kategori produk dengan tfidf vectorizer dan menghitung tingkat kesamaan dengan cosine similarity.

#### Cosine Similarity

Sekarang, dihitung derajat kesamaan (similarity degree) antar nama produk dengan teknik cosine similarity.
"""

from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity(tfidf_matrix)
cosine_sim

"""Dihitung cosine similarity dataframe tfidf_matrix yang  diperoleh pada tahapan sebelumnya. Dengan satu baris kode untuk memanggil fungsi cosine similarity dari library sklearn, hasil similarity tiap nama produk sudah didapat, hasilnya berupa matriks kesamaan dalam bentuk array."""

cosine_sim_df = pd.DataFrame(cosine_sim, index=products['Name'], columns=products['Name'])
print('Shape:', cosine_sim_df.shape)

cosine_sim_df.sample(20, axis=1).sample(20, axis=0)

"""Dengan cosine similarity, berhasil mengidentifikasi kesamaan antar produk lainnya. Shape (7636, 7636) merupakan ukuran matriks similarity dari data. Namun, dalam output, hanya menampilkan sebanyak 20 sampel data saja.


Contoh: angka 1.0 pada Skin Buddy Dot Burst Face Wash dan Bio Renew Deep Cleanser menunjukkan dua produk ini memiliki kesamaan. Begitu juga, dengan Oh! So Bright Serum dengan Skin'o'tic Serum, yang juga mendapat nilai 1.0

#### Mendapatkan Rekomendasi

Sistem rekomendasi akan memberikan produk yang memiliki similarity terhadap produk yang diinput oleh pengguna berdasarkan kesamaan kategori dari produk-produk rekomendasi, hasil similarity tiap produk sudah didapat dari perhitungan sebelumnya.
"""

def products_recommendations(nama_produk, similarity_data=cosine_sim_df, items=products[['Name', 'Location', 'Seller Name']], k=10):
    """
    Rekomendasi Produk Berdasarkan Kesamaan Nama Produk.
    """
    # Mengambil data dengan similarity terbesar dari index yang diinputkan
    index = similarity_data.loc[:,nama_produk].to_numpy().argpartition(
        range(-1, -k-1, -1))

    # Mengambil data dengan similarity terbesar dari index yang diinputkan
    closest = similarity_data.columns[index[-1:-(k+2):-1]]

    # Drop nama_produk agar nama produk yang dicari tidak muncul dalam daftar rekomendasi
    closest = closest.drop(nama_produk, errors='ignore')

    # Membuat dataframe dari data rekomendasi
    recommendations = pd.DataFrame(closest, columns=['Name']).merge(items, on='Name') # Changed 'product_name' to 'Name' for merging

    return recommendations.head(k)

"""Dibuat fungsi dengan nama products_recommendations, dengan nama_produk sebagai parameter pencarian, hasil kesamaan yang diambil dari cosine_sim_df, isi dari dataframe yang ingin ditampilkan dan k (jumlah rekomendasi yang diinginkan) sebanyak 10.

Lalu membuat index untuk mengambil urutan indeks produk yang paling mirip, dengan similarity_data, dengan fungsi argpartition untuk mengurutkan indeks array berdasarkan skor kemiripan dari yang tertinggi ke terendah (berdasarkan parameter range(-1, -k-1, -1)).

Daftar produk disimpan dalam closest, dengan mengambil skor kemiripan tertinggi, lalu menghapus nama produk itu sendiri dari daftar rekomendasi. terakhir, dibuat variabel recommendation, untuk membuat dataframe dari data closest, column, dan items untuk digabung menjadi satu, dan nilai k dikembalikan.
"""

products['Name'].unique()

products[products.Name.eq('OPPO A58 6/128GB Garansi Resmi Indonesia')]

"""Output rekomendasi diharapkan akan memberikan produk serupa "OPPO A58 6/128GB Garansi Resmi Indonesia", dengan kategori produk yang mirip"""

products_recommendations('OPPO A58 6/128GB Garansi Resmi Indonesia')

"""Output pun menampilkan 10 daftar produk rekomendasi yang memiliki kemiripan dengan "OPPO A58 6/128GB Garansi Resmi Indonesia", dengan Nama Seller dan asal seller nya juga

Menguji dengan nama produk lain
"""

products_recommendations('Infinix Note 40 8/256GB - Up to 16GB Extended RAM - Helio G99 - 6.78" FHD+ Amoled 120HZ- 45 Watt Fast Charge - NFC')

products_recommendations('Official Redmi A3 | Layar Muluz 90 Hz berukuran 6.71" kapasitas baterai 5000 mAH')

"""## Model Development dengan Content Based Filtering berdasarkan Rating Produk

Teknik content based filtering akan merekomendasikan item yang mirip dengan item yang disukai pengguna di masa lalu. Pada tahap ini, ditemukan representasi fitur penting dari setiap kategori produk dengan tfidf vectorizer dan menghitung tingkat kesamaan berdasarkan rating dengan cosine similarity.

### Data Preparation

##### TF-IDF Vectorizer

Teknik TF-IDF digunakan pada sistem rekomendasi untuk menemukan representasi fitur penting dari setiap kategori produk.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
tf.fit(products['Name'])
tf.get_feature_names_out()

tfidf_matrix = tf.fit_transform(products['Name'])
tfidf_matrix.shape

"""### Pemodelan

##### Cosine Similarity

Sekarang, dihitung derajat kesamaan (similarity degree) antar rating dari kategori yang sama pada produk dengan teknik cosine similarity.
"""

total_rating = products[['Rating Score']].values
combined_features = np.hstack([total_rating, tfidf_matrix.toarray()])
cosine_sim_rating = cosine_similarity(combined_features)

"""Pada tahapan ini, dihitung cosine similarity dataframe tfidf_matrix yang diperoleh sebelumnya, lalu menyimpan nilai rating dalam variabel total_rating, dan menggabungkan dalam bentuk array dari hasil tfidf_matrix dengan nilai rating yang sudah disimpan"""

cosine_sim_df_2 = pd.DataFrame(cosine_sim_rating, index=products['Name'], columns=products['Name'])
print('Shape:', cosine_sim_df_2.shape)

cosine_sim_df_2.sample(20, axis=1).sample(20, axis=0)

"""Dengan cosine similarity, berhasil mengidentifikasi kesamaan antar produk lainnya. Shape (1720, 1720) merupakan ukuran matriks similarity dari data. Namun, dalam output, hanya menampilkan sebanyak 20 sampel data saja.


Contoh: angka 	0.961239 pada "Apple iPhone 14" dan "Samsung Galaxy A15 5G 8/256GB" menunjukkan dua produk ini memiliki kesamaan kategori dan rating yang serupa

##### Mendapatkan Rekomendasi

Sistem rekomendasi akan memberikan produk yang memiliki similarity terhadap produk yang diinput oleh pengguna berdasarkan kesamaan kategori dan rating yang paling tinggi dari produk-produk rekomendasi, hasil similarity tiap produk sudah didapat dari perhitungan sebelumnya.
"""

def products_recommendations_by_rating(nama_produk, similarity_data=cosine_sim_df_2, items=products[['Name', 'Location', 'Seller Name',
                                                                                                     'Rating Score']], k=10):
    index = similarity_data.loc[:,nama_produk].to_numpy().argpartition(
        range(-1, -k-1, -1))

    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    closest = closest.drop(nama_produk, errors='ignore')
    recommendations = pd.DataFrame(closest, columns=['Name']).merge(items, on='Name')
    recommendations = recommendations.sort_values(by='Rating Score', ascending=False)

    return recommendations.head(k)

"""Dibuat fungsi dengan nama products_recommendations, dengan nama_produk sebagai parameter pencarian, hasil kesamaan yang diambil dari cosine_sim_df, isi dari dataframe yang ingin ditampilkan dan k (jumlah rekomendasi yang diinginkan) sebanyak 10.

Lalu membuat index untuk mengambil urutan indek produk yang paling mirip, dengan similarity_data, dengan fungsi argpartition untuk mengurutkan indeks array berdasarkan skor kemiripan dari yang tertinggi ke terendah (berdasarkan parameter range(-1, -k-1, -1)).

Daftar produk disimpan dalam closest, dengan mengambil skor kemiripan tertinggi, lalu menghapus nama produk itu sendiri dari daftar rekomendasi. terakhir, dibuat variabel recommendation, untuk membuat dataframe dari data closest, column, dan items untuk digabung menjadi satu, diberikan tambahan untuk mengurutkan produk rekomendasi dari rating yang paling tinggi dan nilai k dikembalikan.
"""

products['Name'].unique()

products[products.Name.eq('Official Redmi A3 | Layar Muluz 90 Hz berukuran 6.71" kapasitas baterai 5000 mAH')]

"""Output rekomendasi diharapkan akan memberikan produk serupa "Official Redmi A3 | Layar Muluz 90 Hz berukuran 6.71" kapasitas baterai 5000 mAH", dengan kategori yang mirip."""

products_recommendations_by_rating('Official Redmi A3 | Layar Muluz 90 Hz berukuran 6.71" kapasitas baterai 5000 mAH')

"""Output pun menampilkan 10 daftar produk rekomendasi yang memiliki kemiripan dengan "Official Redmi A3 | Layar Muluz 90 Hz berukuran 6.71" kapasitas baterai 5000 mAH", dengan nama seller, asal seller, dan nilai rating dari yang paling tinggi ke terendah"""

products_recommendations_by_rating('OPPO A58 6/128GB Garansi Resmi Indonesia')

"""## Model Development dengan Content Based Filtering berdasarkan Price (IDR)

Teknik content based filtering akan merekomendasikan item berdasarkan harga. Pada tahap ini, ditemukan representasi fitur penting dari setiap kategori produk dengan tfidf vectorizer dan menghitung tingkat kesamaan berdasarkan total rekomendasi dengan cosine similarity.

### Data Preparation

##### TF-IDF Vectorizer

Teknik TF-IDF digunakan pada sistem rekomendasi untuk menemukan representasi fitur penting dari setiap kategori produk.
"""

products

from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
tf.fit(products['Name'])
tf.get_feature_names_out()

tfidf_matrix = tf.fit_transform(products['Name'])
tfidf_matrix.shape

"""### Pemodelan

##### Cosine Similarity

Sekarang, dihitung derajat kesamaan (similarity degree) antar total rekomendasi dari kategori yang sama pada produk dengan teknik cosine similarity.
"""

total_recommended_count = products[['Price (IDR)']].values
combined_features = np.hstack([total_recommended_count, tfidf_matrix.toarray()])
cosine_sim_recom = cosine_similarity(combined_features)

"""Pada tahapan ini, dihitung cosine similarity dataframe tfidf_matrix yang diperoleh sebelumnya, lalu menyimpan total rekomendasi dalam variabel total_recommended_count, dan menggabungkan dalam bentuk array dari hasil tfidf_matrix dengan total rekomendasi yang sudah disimpan"""

cosine_sim_df_3 = pd.DataFrame(cosine_sim_recom, index=products['Name'], columns=products['Name'])
print('Shape:', cosine_sim_df_3.shape)

cosine_sim_df_3.sample(20, axis=1).sample(20, axis=0)

"""Dengan cosine similarity, berhasil mengidentifikasi kesamaan antar produk lainnya. Shape (1720, 1720) merupakan ukuran matriks similarity dari data. Namun, dalam output, hanya menampilkan sebanyak 20 sampel data saja.


Contoh: angka 	0.961239 pada "Apple iPhone 14" dan "Samsung Galaxy A15 5G 8/256GB" menunjukkan dua produk ini memiliki kesamaan kategori dan rating yang serupa

##### Mendapatkan Rekomendasi

Sistem rekomendasi akan memberikan produk yang memiliki similarity terhadap produk yang diinput oleh pengguna berdasarkan kesamaan kategori dan rating yang paling tinggi dari produk-produk rekomendasi, hasil similarity tiap produk sudah didapat dari perhitungan sebelumnya.
"""

def products_recommendations_by_count_recom(nama_produk, similarity_data=cosine_sim_df_2, items=products[['Name', 'Location', 'Seller Name',
                                                                                                     'Price (IDR)']], k=10):
    index = similarity_data.loc[:,nama_produk].to_numpy().argpartition(
        range(-1, -k-1, -1))

    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    closest = closest.drop(nama_produk, errors='ignore')
    recommendations = pd.DataFrame(closest, columns=['Name']).merge(items, on='Name')
    recommendations = recommendations.sort_values(by='Price (IDR)', ascending=False)

    return recommendations.head(k)

"""Dibuat fungsi dengan nama products_recommendations, dengan nama_produk sebagai parameter pencarian, hasil kesamaan yang diambil dari cosine_sim_df, isi dari dataframe yang ingin ditampilkan dan k (jumlah rekomendasi yang diinginkan) sebanyak 10.

Lalu membuat index untuk mengambil urutan indek produk yang paling mirip, dengan similarity_data, dengan fungsi argpartition untuk mengurutkan indeks array berdasarkan skor kemiripan dari yang tertinggi ke terendah (berdasarkan parameter range(-1, -k-1, -1)).

Daftar produk disimpan dalam closest, dengan mengambil skor kemiripan tertinggi, lalu menghapus nama produk itu sendiri dari daftar rekomendasi. terakhir, dibuat variabel recommendation, untuk membuat dataframe dari data closest, column, dan items untuk digabung menjadi satu, diberikan tambahan untuk mengurutkan produk rekomendasi dari total rekomendasi yang paling banyak dan nilai k dikembalikan.
"""

products['Name'].unique()

products[products.Name.eq('OPPO A58 6/128GB Garansi Resmi Indonesia')]

"""Output rekomendasi diharapkan akan memberikan produk serupa "OPPO A58 6/128GB Garansi Resmi Indonesia", dengan kategori yang mirip"""

products_recommendations_by_count_recom('OPPO A58 6/128GB Garansi Resmi Indonesia')

"""Output pun menampilkan 10 daftar produk rekomendasi yang memiliki kemiripan dengan "OPPO A58 6/128GB Garansi Resmi Indonesia", dengan rentang harga, asal brandnya, dan total rekomendasi dari yang paling mahal ke yang murah."""

products_recommendations_by_count_recom('Official Redmi A3 | Layar Muluz 90 Hz berukuran 6.71" kapasitas baterai 5000 mAH')

